name: Release and upload mod files

on:
  release: 
    types: [created]

jobs:
  build-master:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - uses: actions/github-script@v2
      id: fname
      with:
        result-encoding: string
        script: |
          const fs = require("fs")
          return fs.readdirSync("./build/libs/").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && e.endsWith(".jar"))[0].replace(".jar", "");
      
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: ./build/libs/${{ steps.fname.outputs.result }}.jar application/jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to curseforge
      uses: itsmeow/curseforge-upload@v2
      with:
        token: ${{ secrets.CURSEFORGE_TOKEN }}
        project_id: 403185
        game_endpoint: minecraft
        file_path: ./build/libs/${{ steps.fname.outputs.result }}.jar
        changelog: See the github release for changes.
        display_name: ${{ steps.fname.outputs.result }}
        game_versions: 70886:1.16.3,2:Java 8,68441:Fabric
        release_type: release
        relations: modmenu:optionalDependency
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.fname.outputs.result }}
        path: ./build/libs/*
