name: Release and upload mod files

on:
  release: 

jobs:
  build-master:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Read minecraft version
      uses: christian-draeger/read-properties@1.0.1
      id: read_minecraft_version
      with:
        path: 'gradle.properties'
        property: 'minecraft_version'
    - uses: actions/github-script@v2
      id: fname
      with:
        result-encoding: string
        script: |
          const fs = require("fs")
          return fs.readdirSync("./build/libs/").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && e.endsWith(".jar"))[0].replace(".jar", "");
      
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: ./build/libs/${{ steps.fname.outputs.result }}.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to curseforge
      uses: itsmeow/curseforge-upload@v2
      with:
        token: ${{ secrets.CURSEFORGE_TOKEN }}
        project_id: 403185
        game_endpoint: minecraft
        file_path: ./build/libs/${{ steps.fname.outputs.result }}.jar
        changelog: See the github release for changes.
        display_name: ${{ steps.fname.outputs.result }}
        # 70886 is the minecraft version field
        # 2 is the Java Version field
        # 68441 is the Mod loader field
        game_versions: 70886:${{ steps.read_minecraft_version.outputs.value }},2:Java 8,68441:Fabric
        release_type: release
        relations: modmenu:optionalDependency
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.fname.outputs.result }}
        path: ./build/libs/*
