name: "Release and upload mod files"

on:
  release:

jobs:
  build-master:
    runs-on: "ubuntu-latest"

    steps:
      # Checkout master branch
      - uses: "actions/checkout@v2"
        with:
          ref: "master"

      # Set up JDK for Gradle
      - name: "Set up JDK 1.8"
        uses: "actions/setup-java@v1"
        with:
          java-version: 1.8

      # Grant permission for gradle build
      - name: "Grant execute permission for gradlew"
        run: "chmod +x gradlew"

      # Build mod using gradle
      - name: "Build with Gradle"
        run: "./gradlew build"

      # Read minecraft version from gradle.properties
      - name: "Read minecraft version"
        uses: "christian-draeger/read-properties@1.0.1"
        id: "read_minecraft_version"
        with:
          path: "gradle.properties"
          property: "minecraft_version"

      # This script finds the java archive of the mod
      - uses: "actions/github-script@v2"
        id: "find_mod_jar"
        with:
          result-encoding: "string"
          script: |
            const fs = require("fs")
            return fs.readdirSync("./build/libs/").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && e.endsWith(".jar"))[0].replace(".jar", "");

      # This script finds the development java archive of the mod
      - uses: "actions/github-script@v2"
        id: "find_mod_dev_jar"
        with:
          result-encoding: "string"
          script: |
            const fs = require("fs")
            return fs.readdirSync("./build/libs/").filter(e => e.endsWith("dev.jar"))[0].replace(".jar", "");

      # This script finds the sources java archive of the mod
      - uses: "actions/github-script@v2"
        id: "find_mod_sources_jar"
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            return fs.readdirSync("./build/libs/").filter(e => e.endsWith("sources.jar"))[0].replace(".jar", "");

      # Upload the main asset to the previous created release
      - name: "Upload mod asset to release"
        uses: "actions/upload-release-asset@v1.0.2"
        with:
          upload_url: "${{ github.event.release.upload_url }}"
          asset_path: "./build/libs/${{ steps.find_mod_jar.outputs.result }}.jar"
          asset_name: "${{ steps.find_mod_jar.outputs.result }}"
          asset_content_type: "application/java-archive"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # Upload the source asset to the previous created release
      - name: "Upload mod sources asset to release"
        uses: "actions/upload-release-asset@v1.0.2"
        with:
          upload_url: "${{ github.event.release.upload_url }}"
          asset_path: "./build/libs/${{ steps.find_mod_sources_jar.outputs.result }}.jar"
          asset_name: "${{ steps.find_mod_sources_jar.outputs.result }}"
          asset_content_type: "application/java-archive"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # Upload the development asset to the previous created release
      - name: "Upload mod dev asset to release"
        uses: "actions/upload-release-asset@v1.0.2"
        with:
          upload_url: "${{ github.event.release.upload_url }}"
          asset_path: "./build/libs/${{ steps.find_mod_dev_jar.outputs.result }}.jar"
          asset_name: "${{ steps.find_mod_dev_jar.outputs.result }}"
          asset_content_type: "application/java-archive"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # Upload the main asset to curseforge
      - name: "Upload to curseforge"
        uses: "itsmeow/curseforge-upload@v2"
        with:
          token: "${{ secrets.CURSEFORGE_TOKEN }}"
          project_id: 403185
          game_endpoint: "minecraft"
          file_path: "./build/libs/${{ steps.find_mod_jar.outputs.result }}.jar"
          changelog: "See the github release for changes"
          display_name: "${{ steps.find_mod_jar.outputs.result }}"

          # 70886 is the minecraft version field
          # 2 is the Java Version field
          # 68441 is the Mod loader field
          game_versions: "70886:${{ steps.read_minecraft_version.outputs.value }},2:Java 8,68441:Fabric"
          release_type: "release"
          relations: "modmenu:optionalDependency"

      # Upload the main asset to workflow artifact
      - uses: "actions/upload-artifact@v2"
        with:
          name: "${{ steps.find_mod_jar.outputs.result }}.jar"
          path: "./build/libs/${{ steps.find_mod_jar.outputs.result }}"

      # Upload the source asset to workflow artifact
      - uses: "actions/upload-artifact@v2"
        with:
          name: "${{ steps.find_mod_sources_jar.outputs.result }}.jar"
          path: "./build/libs/${{ steps.find_mod_sources_jar.outputs.result }}.jar"

      # Upload the dev asset to workflow artifact
      - uses: "actions/upload-artifact@v2"
        with:
          name: "${{ steps.find_mod_dev_jar.outputs.result }}.jar"
          path: "./build/libs/${{ steps.find_mod_dev_jar.outputs.result }}.jar"
